"""Add password column to sellers table

Revision ID: 0b9d86192095
Revises: 11269c2ada9a
Create Date: 2024-11-29 17:04:15.335785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b9d86192095'
down_revision: Union[str, None] = '11269c2ada9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_supplier')
    op.add_column('suppliers', sa.Column('seller_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'suppliers', 'sellers', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'seller_id')
    op.create_table('category_supplier',
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='category_supplier_category_id_fkey'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name='category_supplier_supplier_id_fkey'),
    sa.PrimaryKeyConstraint('category_id', 'supplier_id', name='category_supplier_pkey')
    )
    # ### end Alembic commands ###
