"""Add password column to sellers table

Revision ID: 11269c2ada9a
Revises: 9d78702fae33
Create Date: 2024-11-29 17:00:56.483241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11269c2ada9a'
down_revision: Union[str, None] = '9d78702fae33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_seller_id_fkey', 'categories', type_='foreignkey')
    op.drop_column('categories', 'seller_id')
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.drop_constraint('suppliers_category_id_fkey', 'suppliers', type_='foreignkey')
    op.drop_constraint('suppliers_seller_id_fkey', 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'seller_id')
    op.drop_column('suppliers', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('suppliers_seller_id_fkey', 'suppliers', 'sellers', ['seller_id'], ['id'])
    op.create_foreign_key('suppliers_category_id_fkey', 'suppliers', 'categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'category_id')
    op.add_column('categories', sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('categories_seller_id_fkey', 'categories', 'sellers', ['seller_id'], ['id'])
    # ### end Alembic commands ###
