"""Add password column to sellers table

Revision ID: 1d5ad5bf92bf
Revises: 530e74e7d7c3
Create Date: 2024-11-29 13:12:58.886097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d5ad5bf92bf'
down_revision: Union[str, None] = '530e74e7d7c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
