"""Add password column to sellers table

Revision ID: 37a379d7c658
Revises: 0b9d86192095
Create Date: 2024-11-29 17:12:21.270178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a379d7c658'
down_revision: Union[str, None] = '0b9d86192095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_category',
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='supplier_category_category_id_fkey'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name='supplier_category_supplier_id_fkey'),
    sa.PrimaryKeyConstraint('supplier_id', 'category_id', name='supplier_category_pkey')
    )
    # ### end Alembic commands ###
