"""Add password column to sellers table

Revision ID: 47f3ae2c0110
Revises: eab97bb40775
Create Date: 2024-11-29 16:46:43.146289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f3ae2c0110'
down_revision: Union[str, None] = 'eab97bb40775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('suppliers', 'description')
    op.drop_column('suppliers', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('suppliers', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('products', 'description')
    op.drop_column('products', 'price')
    # ### end Alembic commands ###
