"""Fixed Category-Supplier backref conflict

Revision ID: 530e74e7d7c3
Revises: fd60fade2f4c
Create Date: 2024-11-29 12:55:47.291002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '530e74e7d7c3'
down_revision: Union[str, None] = 'fd60fade2f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
