"""Add password column to sellers table

Revision ID: 58348ce61f1c
Revises: aa941db2d2a6
Create Date: 2024-11-29 20:32:19.516161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58348ce61f1c'
down_revision: Union[str, None] = 'aa941db2d2a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_supplier')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_supplier',
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='category_supplier_category_id_fkey'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name='category_supplier_supplier_id_fkey'),
    sa.PrimaryKeyConstraint('category_id', 'supplier_id', name='category_supplier_pkey')
    )
    # ### end Alembic commands ###
