"""Add password column to sellers table

Revision ID: 5d905059132f
Revises: 58348ce61f1c
Create Date: 2024-11-29 20:47:28.890209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d905059132f'
down_revision: Union[str, None] = '58348ce61f1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('seller_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'categories', 'sellers', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'seller_id')
    # ### end Alembic commands ###
