"""Add password column to sellers table

Revision ID: 71f3a0efd3e8
Revises: 37b6acc71909
Create Date: 2024-11-29 20:00:18.712166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71f3a0efd3e8'
down_revision: Union[str, None] = '37b6acc71909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
