"""Add password column to sellers table

Revision ID: 831f6be682ce
Revises: 1f2c1a3294b6
Create Date: 2024-11-29 22:29:02.185805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '831f6be682ce'
down_revision: Union[str, None] = '1f2c1a3294b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
