"""Add password column to sellers table

Revision ID: 9d78702fae33
Revises: 47f3ae2c0110
Create Date: 2024-11-29 16:56:26.369268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d78702fae33'
down_revision: Union[str, None] = '47f3ae2c0110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('manufacturer', sa.String(), nullable=False))
    op.drop_constraint('products_category_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'category_id')
    op.drop_column('products', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('products_category_id_fkey', 'products', 'categories', ['category_id'], ['id'])
    op.drop_column('products', 'manufacturer')
    # ### end Alembic commands ###
