"""Add password column to sellers table

Revision ID: aa941db2d2a6
Revises: 71f3a0efd3e8
Create Date: 2024-11-29 20:24:45.968677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa941db2d2a6'
down_revision: Union[str, None] = '71f3a0efd3e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
