"""Fix Category-Supplier Relationship

Revision ID: b05339d91df8
Revises: 2c0beb31c1de
Create Date: 2024-11-29 11:58:33.376416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b05339d91df8'
down_revision: Union[str, None] = '2c0beb31c1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'categories', ['name'])
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('sellers', sa.Column('password', sa.String(length=100), nullable=False))
    op.alter_column('sellers', 'username',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('sellers', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('sellers', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
    op.drop_index('ix_sellers_id', table_name='sellers')
    op.drop_index('ix_sellers_username', table_name='sellers')
    op.create_unique_constraint(None, 'sellers', ['username'])
    op.drop_column('sellers', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('hashed_password', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sellers', type_='unique')
    op.create_index('ix_sellers_username', 'sellers', ['username'], unique=True)
    op.create_index('ix_sellers_id', 'sellers', ['id'], unique=False)
    op.alter_column('sellers', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('sellers', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('sellers', 'username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('sellers', 'password')
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'categories', type_='unique')
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
