"""initial migration

Revision ID: d5ebe025fdb7
Revises: 2aa134f361b1
Create Date: 2024-11-29 10:08:10.389874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ebe025fdb7'
down_revision: Union[str, None] = '2aa134f361b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'categories', ['name'])
    op.create_foreign_key(None, 'categories', 'sellers', ['seller_id'], ['id'])
    op.add_column('products', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('description', sa.String(), nullable=True))
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    op.create_foreign_key(None, 'products', 'sellers', ['seller_id'], ['id'])
    op.create_unique_constraint(None, 'suppliers', ['name'])
    op.drop_column('suppliers', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_column('products', 'description')
    op.drop_column('products', 'seller_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_column('categories', 'seller_id')
    # ### end Alembic commands ###
