"""Add password column to sellers table

Revision ID: dcdb2e1528ca
Revises: 79f364b6a497
Create Date: 2024-11-29 15:31:54.419995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcdb2e1528ca'
down_revision: Union[str, None] = '79f364b6a497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_products')
    op.alter_column('suppliers', 'seller_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'seller_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('supplier_products',
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='supplier_products_product_id_fkey'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name='supplier_products_supplier_id_fkey'),
    sa.PrimaryKeyConstraint('supplier_id', 'product_id', name='supplier_products_pkey')
    )
    # ### end Alembic commands ###
