"""Add password column to sellers table

Revision ID: e52beee8266b
Revises: dcdb2e1528ca
Create Date: 2024-11-29 15:47:07.874963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52beee8266b'
down_revision: Union[str, None] = 'dcdb2e1528ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('products_seller_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'seller_id')
    op.drop_column('products', 'description')
    op.drop_column('products', 'manufacturer')
    op.drop_column('products', 'price')
    op.add_column('supplier_products', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('supplier_products', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_products', 'description')
    op.drop_column('supplier_products', 'price')
    op.add_column('products', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('manufacturer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_seller_id_fkey', 'products', 'sellers', ['seller_id'], ['id'])
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
