"""Add password column to sellers table

Revision ID: eab97bb40775
Revises: e52beee8266b
Create Date: 2024-11-29 16:30:37.067686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab97bb40775'
down_revision: Union[str, None] = 'e52beee8266b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seller_products')
    op.drop_table('supplier_products')
    op.drop_table('Supplier_products')
    op.add_column('products', sa.Column('seller_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'sellers', ['seller_id'], ['id'])
    op.add_column('suppliers', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('suppliers', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'description')
    op.drop_column('suppliers', 'price')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'seller_id')
    op.create_table('Supplier_products',
    sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='Supplier_products_product_id_fkey'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name='Supplier_products_seller_id_fkey'),
    sa.PrimaryKeyConstraint('seller_id', 'product_id', name='Supplier_products_pkey')
    )
    op.create_table('supplier_products',
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='supplier_products_product_id_fkey'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name='supplier_products_supplier_id_fkey'),
    sa.PrimaryKeyConstraint('supplier_id', 'product_id', name='supplier_products_pkey')
    )
    op.create_table('seller_products',
    sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='seller_products_product_id_fkey'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name='seller_products_seller_id_fkey'),
    sa.PrimaryKeyConstraint('seller_id', 'product_id', name='seller_products_pkey')
    )
    # ### end Alembic commands ###
