"""Add password column to sellers table

Revision ID: f50e2415650e
Revises: 9da9dd556081
Create Date: 2024-11-29 21:46:43.760414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50e2415650e'
down_revision: Union[str, None] = '9da9dd556081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('suppliers', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('suppliers', sa.Column('address', sa.String(length=500), nullable=False))
    op.add_column('suppliers', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_suppliers_category_id'), 'suppliers', ['category_id'], unique=False)
    op.create_index(op.f('ix_suppliers_seller_id'), 'suppliers', ['seller_id'], unique=False)
    op.create_foreign_key(None, 'suppliers', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_index(op.f('ix_suppliers_seller_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_category_id'), table_name='suppliers')
    op.drop_column('suppliers', 'category_id')
    op.drop_column('suppliers', 'address')
    op.drop_column('suppliers', 'phone')
    op.drop_column('suppliers', 'email')
    # ### end Alembic commands ###
